#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 128
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 66
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 14
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 14

enum {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_fn = 3,
  anon_sym_COLON = 4,
  anon_sym_extern = 5,
  anon_sym_LPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_RPAREN = 8,
  anon_sym_String = 9,
  anon_sym_Boolean = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_let = 13,
  anon_sym_EQ = 14,
  anon_sym_if = 15,
  anon_sym_else = 16,
  anon_sym_while = 17,
  anon_sym_return = 18,
  anon_sym_BANG = 19,
  anon_sym_select = 20,
  anon_sym_as = 21,
  anon_sym_EQ_GT = 22,
  anon_sym_DQUOTE = 23,
  aux_sym_string_literal_token1 = 24,
  anon_sym_SQUOTE_SQUOTE_SQUOTE = 25,
  aux_sym_string_literal_token2 = 26,
  sym_escape_sequence = 27,
  anon_sym_true = 28,
  anon_sym_false = 29,
  sym_placeholder = 30,
  sym_source_file = 31,
  sym_definition = 32,
  sym_function_declaration = 33,
  sym_external_function_declaration = 34,
  sym_parameter_list = 35,
  sym_parameter = 36,
  sym_type = 37,
  sym_unit_type = 38,
  sym_block = 39,
  sym_statement = 40,
  sym_let_declaration = 41,
  sym_variable_assignment = 42,
  sym_if_statement = 43,
  sym_while_statement = 44,
  sym_return_statement = 45,
  sym_injection = 46,
  sym_expression_statement = 47,
  sym_expression = 48,
  sym_if_else_expression = 49,
  sym__simple_expression = 50,
  sym_function_call = 51,
  sym_argument_list = 52,
  sym_argument = 53,
  sym_select_expression = 54,
  sym_select_clause = 55,
  sym_string_literal = 56,
  sym_boolean_literal = 57,
  aux_sym_source_file_repeat1 = 58,
  aux_sym_function_declaration_repeat1 = 59,
  aux_sym_parameter_list_repeat1 = 60,
  aux_sym_block_repeat1 = 61,
  aux_sym_argument_list_repeat1 = 62,
  aux_sym_select_expression_repeat1 = 63,
  aux_sym_string_literal_repeat1 = 64,
  aux_sym_string_literal_repeat2 = 65,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_fn] = "fn",
  [anon_sym_COLON] = ":",
  [anon_sym_extern] = "extern",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_String] = "String",
  [anon_sym_Boolean] = "Boolean",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_return] = "return",
  [anon_sym_BANG] = "!",
  [anon_sym_select] = "select",
  [anon_sym_as] = "as",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = "'''",
  [aux_sym_string_literal_token2] = "string_literal_token2",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_placeholder] = "placeholder",
  [sym_source_file] = "source_file",
  [sym_definition] = "definition",
  [sym_function_declaration] = "function_declaration",
  [sym_external_function_declaration] = "external_function_declaration",
  [sym_parameter_list] = "parameter_list",
  [sym_parameter] = "parameter",
  [sym_type] = "type",
  [sym_unit_type] = "unit_type",
  [sym_block] = "block",
  [sym_statement] = "statement",
  [sym_let_declaration] = "let_declaration",
  [sym_variable_assignment] = "variable_assignment",
  [sym_if_statement] = "if_statement",
  [sym_while_statement] = "while_statement",
  [sym_return_statement] = "return_statement",
  [sym_injection] = "injection",
  [sym_expression_statement] = "expression_statement",
  [sym_expression] = "expression",
  [sym_if_else_expression] = "if_else_expression",
  [sym__simple_expression] = "_simple_expression",
  [sym_function_call] = "function_call",
  [sym_argument_list] = "argument_list",
  [sym_argument] = "argument",
  [sym_select_expression] = "select_expression",
  [sym_select_clause] = "select_clause",
  [sym_string_literal] = "string_literal",
  [sym_boolean_literal] = "boolean_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_declaration_repeat1] = "function_declaration_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_select_expression_repeat1] = "select_expression_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
  [aux_sym_string_literal_repeat2] = "string_literal_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_String] = anon_sym_String,
  [anon_sym_Boolean] = anon_sym_Boolean,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_select] = anon_sym_select,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = anon_sym_SQUOTE_SQUOTE_SQUOTE,
  [aux_sym_string_literal_token2] = aux_sym_string_literal_token2,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_placeholder] = sym_placeholder,
  [sym_source_file] = sym_source_file,
  [sym_definition] = sym_definition,
  [sym_function_declaration] = sym_function_declaration,
  [sym_external_function_declaration] = sym_external_function_declaration,
  [sym_parameter_list] = sym_parameter_list,
  [sym_parameter] = sym_parameter,
  [sym_type] = sym_type,
  [sym_unit_type] = sym_unit_type,
  [sym_block] = sym_block,
  [sym_statement] = sym_statement,
  [sym_let_declaration] = sym_let_declaration,
  [sym_variable_assignment] = sym_variable_assignment,
  [sym_if_statement] = sym_if_statement,
  [sym_while_statement] = sym_while_statement,
  [sym_return_statement] = sym_return_statement,
  [sym_injection] = sym_injection,
  [sym_expression_statement] = sym_expression_statement,
  [sym_expression] = sym_expression,
  [sym_if_else_expression] = sym_if_else_expression,
  [sym__simple_expression] = sym__simple_expression,
  [sym_function_call] = sym_function_call,
  [sym_argument_list] = sym_argument_list,
  [sym_argument] = sym_argument,
  [sym_select_expression] = sym_select_expression,
  [sym_select_clause] = sym_select_clause,
  [sym_string_literal] = sym_string_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_declaration_repeat1] = aux_sym_function_declaration_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_select_expression_repeat1] = aux_sym_select_expression_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
  [aux_sym_string_literal_repeat2] = aux_sym_string_literal_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_String] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Boolean] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_select] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_placeholder] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_external_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_unit_type] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_let_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_while_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_injection] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_if_else_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__simple_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_select_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_select_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_select_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_alternative = 1,
  field_arguments = 2,
  field_binding = 3,
  field_body = 4,
  field_call = 5,
  field_condition = 6,
  field_consequence = 7,
  field_function = 8,
  field_name = 9,
  field_parameters = 10,
  field_result = 11,
  field_return_type = 12,
  field_type = 13,
  field_value = 14,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_arguments] = "arguments",
  [field_binding] = "binding",
  [field_body] = "body",
  [field_call] = "call",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_function] = "function",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_result] = "result",
  [field_return_type] = "return_type",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 4},
  [3] = {.index = 6, .length = 3},
  [4] = {.index = 9, .length = 4},
  [5] = {.index = 13, .length = 3},
  [6] = {.index = 16, .length = 2},
  [7] = {.index = 18, .length = 2},
  [8] = {.index = 20, .length = 2},
  [9] = {.index = 22, .length = 2},
  [10] = {.index = 24, .length = 2},
  [11] = {.index = 26, .length = 3},
  [12] = {.index = 29, .length = 3},
  [13] = {.index = 32, .length = 7},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_type, 2},
  [2] =
    {field_body, 5},
    {field_name, 1},
    {field_parameters, 2},
    {field_return_type, 4},
  [6] =
    {field_name, 2},
    {field_parameters, 3},
    {field_return_type, 5},
  [9] =
    {field_body, 6},
    {field_name, 2},
    {field_parameters, 3},
    {field_return_type, 5},
  [13] =
    {field_name, 3},
    {field_parameters, 4},
    {field_return_type, 6},
  [16] =
    {field_arguments, 1},
    {field_function, 0},
  [18] =
    {field_condition, 1},
    {field_consequence, 2},
  [20] =
    {field_body, 2},
    {field_condition, 1},
  [22] =
    {field_name, 0},
    {field_value, 2},
  [24] =
    {field_name, 1},
    {field_value, 3},
  [26] =
    {field_alternative, 4},
    {field_condition, 1},
    {field_consequence, 2},
  [29] =
    {field_binding, 2},
    {field_call, 0},
    {field_result, 4},
  [32] =
    {field_alternative, 6},
    {field_alternative, 7},
    {field_alternative, 8},
    {field_condition, 1},
    {field_consequence, 2},
    {field_consequence, 3},
    {field_consequence, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 5,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 59,
  [67] = 67,
  [68] = 30,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 65,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 31,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 106,
  [126] = 126,
  [127] = 127,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '!') ADVANCE(20);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '\'') ADVANCE(6);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == ',') ADVANCE(14);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '=') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '}') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(20);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '\'') ADVANCE(6);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == '}') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '#') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '=') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '\'') ADVANCE(6);
      if (lookahead == '\\') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '!') ADVANCE(20);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '#') ADVANCE(11);
      if (lookahead == '\'') ADVANCE(6);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == ',') ADVANCE(14);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '=') ADVANCE(19);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '}') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(21);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '#') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_SQUOTE_SQUOTE_SQUOTE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'B') ADVANCE(1);
      if (lookahead == 'S') ADVANCE(2);
      if (lookahead == '_') ADVANCE(3);
      if (lookahead == 'a') ADVANCE(4);
      if (lookahead == 'e') ADVANCE(5);
      if (lookahead == 'f') ADVANCE(6);
      if (lookahead == 'i') ADVANCE(7);
      if (lookahead == 'l') ADVANCE(8);
      if (lookahead == 'r') ADVANCE(9);
      if (lookahead == 's') ADVANCE(10);
      if (lookahead == 't') ADVANCE(11);
      if (lookahead == 'w') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_placeholder);
      END_STATE();
    case 4:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(16);
      if (lookahead == 'x') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 12:
      if (lookahead == 'h') ADVANCE(25);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(34);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(37);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(41);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(44);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(49);
      END_STATE();
    case 42:
      if (lookahead == 'c') ADVANCE(50);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 45:
      if (lookahead == 'a') ADVANCE(52);
      END_STATE();
    case 46:
      if (lookahead == 'g') ADVANCE(53);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(57);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_String);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_select);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_Boolean);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 1},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 3},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_String] = ACTIONS(1),
    [anon_sym_Boolean] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_select] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_placeholder] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(126),
    [sym_definition] = STATE(46),
    [sym_function_declaration] = STATE(63),
    [sym_external_function_declaration] = STATE(63),
    [aux_sym_source_file_repeat1] = STATE(46),
    [aux_sym_function_declaration_repeat1] = STATE(64),
    [sym_comment] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [anon_sym_extern] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(19), 1,
      anon_sym_while,
    ACTIONS(21), 1,
      anon_sym_return,
    ACTIONS(23), 1,
      anon_sym_select,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    STATE(32), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(25), 6,
      sym_if_else_expression,
      sym__simple_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
    STATE(37), 7,
      sym_let_declaration,
      sym_variable_assignment,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
      sym_injection,
      sym_expression_statement,
  [59] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(19), 1,
      anon_sym_while,
    ACTIONS(21), 1,
      anon_sym_return,
    ACTIONS(23), 1,
      anon_sym_select,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(25), 6,
      sym_if_else_expression,
      sym__simple_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
    STATE(37), 7,
      sym_let_declaration,
      sym_variable_assignment,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
      sym_injection,
      sym_expression_statement,
  [118] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(19), 1,
      anon_sym_while,
    ACTIONS(21), 1,
      anon_sym_return,
    ACTIONS(23), 1,
      anon_sym_select,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(25), 6,
      sym_if_else_expression,
      sym__simple_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
    STATE(37), 7,
      sym_let_declaration,
      sym_variable_assignment,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
      sym_injection,
      sym_expression_statement,
  [177] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_RBRACE,
    ACTIONS(40), 1,
      anon_sym_let,
    ACTIONS(43), 1,
      anon_sym_if,
    ACTIONS(46), 1,
      anon_sym_while,
    ACTIONS(49), 1,
      anon_sym_return,
    ACTIONS(52), 1,
      anon_sym_select,
    ACTIONS(55), 1,
      anon_sym_DQUOTE,
    ACTIONS(58), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    STATE(32), 1,
      sym_expression,
    ACTIONS(61), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(25), 6,
      sym_if_else_expression,
      sym__simple_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
    STATE(37), 7,
      sym_let_declaration,
      sym_variable_assignment,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
      sym_injection,
      sym_expression_statement,
  [236] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(19), 1,
      anon_sym_while,
    ACTIONS(21), 1,
      anon_sym_return,
    ACTIONS(23), 1,
      anon_sym_select,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(64), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(25), 6,
      sym_if_else_expression,
      sym__simple_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
    STATE(37), 7,
      sym_let_declaration,
      sym_variable_assignment,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
      sym_injection,
      sym_expression_statement,
  [295] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(19), 1,
      anon_sym_while,
    ACTIONS(21), 1,
      anon_sym_return,
    ACTIONS(23), 1,
      anon_sym_select,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    STATE(29), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(25), 6,
      sym_if_else_expression,
      sym__simple_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
    STATE(37), 7,
      sym_let_declaration,
      sym_variable_assignment,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
      sym_injection,
      sym_expression_statement,
  [354] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_select,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    ACTIONS(72), 1,
      anon_sym_if,
    STATE(39), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(70), 3,
      anon_sym_let,
      anon_sym_while,
      anon_sym_return,
    STATE(25), 6,
      sym_if_else_expression,
      sym__simple_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [396] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(74), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      anon_sym_as,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [420] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_argument_list,
    ACTIONS(82), 6,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(78), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [448] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(84), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      anon_sym_as,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [472] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(88), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      anon_sym_as,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [496] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(92), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      anon_sym_as,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [520] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(96), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [543] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(100), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [566] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(104), 1,
      anon_sym_EQ,
    STATE(12), 1,
      sym_argument_list,
    ACTIONS(82), 4,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(78), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [595] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 7,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(106), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [618] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_select,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_if,
    STATE(119), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 6,
      sym_if_else_expression,
      sym__simple_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [652] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_select,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_if,
    STATE(92), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 6,
      sym_if_else_expression,
      sym__simple_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [686] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_select,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_if,
    STATE(35), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 6,
      sym_if_else_expression,
      sym__simple_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [720] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_select,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_if,
    STATE(107), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 6,
      sym_if_else_expression,
      sym__simple_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [754] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_select,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_if,
    STATE(38), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(25), 6,
      sym_if_else_expression,
      sym__simple_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [788] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 5,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(110), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [809] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 5,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(114), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [830] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 5,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(118), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [851] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 5,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(122), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [872] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 5,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(126), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [893] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_else,
    ACTIONS(132), 3,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(130), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [915] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
    ACTIONS(140), 1,
      anon_sym_BANG,
    ACTIONS(142), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(136), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [939] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 3,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(144), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [959] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 3,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(148), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [979] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_BANG,
    ACTIONS(142), 3,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(136), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1001] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
    ACTIONS(154), 1,
      sym_placeholder,
    STATE(80), 1,
      sym_argument,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(90), 4,
      sym__simple_expression,
      sym_function_call,
      sym_string_literal,
      sym_boolean_literal,
  [1033] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 3,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(156), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1052] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 3,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(160), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1071] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 3,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(164), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1090] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 3,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(168), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1109] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 3,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(172), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1128] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 3,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(176), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1147] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(154), 1,
      sym_placeholder,
    STATE(94), 1,
      sym_argument,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(90), 4,
      sym__simple_expression,
      sym_function_call,
      sym_string_literal,
      sym_boolean_literal,
  [1176] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 3,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(180), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
  [1195] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(109), 4,
      sym__simple_expression,
      sym_function_call,
      sym_string_literal,
      sym_boolean_literal,
  [1218] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(85), 4,
      sym__simple_expression,
      sym_function_call,
      sym_string_literal,
      sym_boolean_literal,
  [1241] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(86), 4,
      sym__simple_expression,
      sym_function_call,
      sym_string_literal,
      sym_boolean_literal,
  [1264] = 7,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
    ACTIONS(186), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_fn,
    ACTIONS(192), 1,
      anon_sym_extern,
    STATE(64), 1,
      aux_sym_function_declaration_repeat1,
    STATE(45), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
    STATE(63), 2,
      sym_function_declaration,
      sym_external_function_declaration,
  [1288] = 7,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      anon_sym_extern,
    ACTIONS(195), 1,
      ts_builtin_sym_end,
    STATE(64), 1,
      aux_sym_function_declaration_repeat1,
    STATE(45), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
    STATE(63), 2,
      sym_function_declaration,
      sym_external_function_declaration,
  [1312] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    STATE(59), 1,
      sym_unit_type,
    STATE(93), 1,
      sym_type,
    ACTIONS(199), 2,
      anon_sym_String,
      anon_sym_Boolean,
  [1329] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    STATE(59), 1,
      sym_unit_type,
    STATE(98), 1,
      sym_type,
    ACTIONS(199), 2,
      anon_sym_String,
      anon_sym_Boolean,
  [1346] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    STATE(59), 1,
      sym_unit_type,
    STATE(83), 1,
      sym_type,
    ACTIONS(199), 2,
      anon_sym_String,
      anon_sym_Boolean,
  [1363] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_LPAREN,
    STATE(66), 1,
      sym_unit_type,
    STATE(70), 1,
      sym_type,
    ACTIONS(203), 2,
      anon_sym_String,
      anon_sym_Boolean,
  [1380] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_LPAREN,
    STATE(62), 1,
      sym_type,
    STATE(66), 1,
      sym_unit_type,
    ACTIONS(203), 2,
      anon_sym_String,
      anon_sym_Boolean,
  [1397] = 4,
    ACTIONS(205), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_DQUOTE,
    STATE(52), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(209), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1411] = 4,
    ACTIONS(205), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_DQUOTE,
    STATE(58), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(214), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1425] = 5,
    ACTIONS(205), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(216), 1,
      aux_sym_string_literal_token2,
    ACTIONS(218), 1,
      sym_escape_sequence,
    STATE(55), 1,
      aux_sym_string_literal_repeat2,
  [1441] = 5,
    ACTIONS(205), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(222), 1,
      aux_sym_string_literal_token2,
    ACTIONS(224), 1,
      sym_escape_sequence,
    STATE(57), 1,
      aux_sym_string_literal_repeat2,
  [1457] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      sym_identifier,
    ACTIONS(228), 1,
      anon_sym_RBRACE,
    STATE(60), 1,
      sym_select_clause,
    STATE(123), 1,
      sym_function_call,
  [1473] = 5,
    ACTIONS(205), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(232), 1,
      aux_sym_string_literal_token2,
    ACTIONS(235), 1,
      sym_escape_sequence,
    STATE(57), 1,
      aux_sym_string_literal_repeat2,
  [1489] = 4,
    ACTIONS(205), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_DQUOTE,
    STATE(52), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(238), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1503] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [1512] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    ACTIONS(244), 1,
      anon_sym_RBRACE,
    STATE(78), 1,
      aux_sym_select_expression_repeat1,
  [1525] = 1,
    ACTIONS(246), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1532] = 1,
    ACTIONS(248), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1539] = 1,
    ACTIONS(250), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1546] = 4,
    ACTIONS(252), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_fn,
    ACTIONS(256), 1,
      anon_sym_extern,
    STATE(74), 1,
      aux_sym_function_declaration_repeat1,
  [1559] = 1,
    ACTIONS(258), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1566] = 1,
    ACTIONS(240), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1573] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_COMMA,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      aux_sym_argument_list_repeat1,
  [1586] = 1,
    ACTIONS(146), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1593] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    ACTIONS(268), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_select_expression_repeat1,
  [1606] = 1,
    ACTIONS(270), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1613] = 1,
    ACTIONS(272), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1620] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [1629] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_COMMA,
    ACTIONS(277), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_parameter_list_repeat1,
  [1642] = 3,
    ACTIONS(279), 1,
      sym_comment,
    STATE(74), 1,
      aux_sym_function_declaration_repeat1,
    ACTIONS(282), 2,
      anon_sym_fn,
      anon_sym_extern,
  [1653] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      sym_identifier,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      sym_parameter,
  [1666] = 1,
    ACTIONS(150), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1673] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_COMMA,
    ACTIONS(290), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      aux_sym_argument_list_repeat1,
  [1686] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    ACTIONS(292), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_select_expression_repeat1,
  [1699] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      sym_identifier,
    STATE(97), 1,
      sym_select_clause,
    STATE(123), 1,
      sym_function_call,
  [1712] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_COMMA,
    ACTIONS(294), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      aux_sym_argument_list_repeat1,
  [1725] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_COMMA,
    ACTIONS(298), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_parameter_list_repeat1,
  [1738] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_parameter_list_repeat1,
  [1751] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1759] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_LPAREN,
    STATE(120), 1,
      sym_parameter_list,
  [1769] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_LBRACE,
    STATE(28), 1,
      sym_block,
  [1779] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      anon_sym_LBRACE,
    STATE(36), 1,
      sym_block,
  [1789] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_argument_list,
  [1799] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_LPAREN,
    STATE(103), 1,
      sym_parameter_list,
  [1809] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      sym_identifier,
    STATE(95), 1,
      sym_parameter,
  [1819] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1827] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_LPAREN,
    STATE(104), 1,
      sym_parameter_list,
  [1837] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1845] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_LBRACE,
    STATE(61), 1,
      sym_block,
  [1855] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1863] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1871] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      anon_sym_LBRACE,
    STATE(41), 1,
      sym_block,
  [1881] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1889] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_LBRACE,
    STATE(71), 1,
      sym_block,
  [1899] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_LPAREN,
    STATE(118), 1,
      sym_parameter_list,
  [1909] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      anon_sym_LBRACE,
  [1916] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 1,
      anon_sym_fn,
  [1923] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      anon_sym_EQ,
  [1930] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      anon_sym_COLON,
  [1937] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      anon_sym_COLON,
  [1944] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      anon_sym_else,
  [1951] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      anon_sym_RPAREN,
  [1958] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
  [1965] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 1,
      anon_sym_EQ_GT,
  [1972] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      anon_sym_LBRACE,
  [1979] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      sym_identifier,
  [1986] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      anon_sym_COLON,
  [1993] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      anon_sym_COLON,
  [2000] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(340), 1,
      sym_identifier,
  [2007] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(342), 1,
      anon_sym_COLON,
  [2014] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(344), 1,
      anon_sym_LBRACE,
  [2021] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(346), 1,
      sym_identifier,
  [2028] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      sym_identifier,
  [2035] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(350), 1,
      anon_sym_COLON,
  [2042] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(352), 1,
      anon_sym_RBRACE,
  [2049] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(354), 1,
      anon_sym_COLON,
  [2056] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(356), 1,
      sym_identifier,
  [2063] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(358), 1,
      sym_identifier,
  [2070] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(360), 1,
      anon_sym_as,
  [2077] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(362), 1,
      anon_sym_COLON,
  [2084] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(364), 1,
      anon_sym_RPAREN,
  [2091] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(366), 1,
      ts_builtin_sym_end,
  [2098] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(368), 1,
      anon_sym_fn,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 59,
  [SMALL_STATE(4)] = 118,
  [SMALL_STATE(5)] = 177,
  [SMALL_STATE(6)] = 236,
  [SMALL_STATE(7)] = 295,
  [SMALL_STATE(8)] = 354,
  [SMALL_STATE(9)] = 396,
  [SMALL_STATE(10)] = 420,
  [SMALL_STATE(11)] = 448,
  [SMALL_STATE(12)] = 472,
  [SMALL_STATE(13)] = 496,
  [SMALL_STATE(14)] = 520,
  [SMALL_STATE(15)] = 543,
  [SMALL_STATE(16)] = 566,
  [SMALL_STATE(17)] = 595,
  [SMALL_STATE(18)] = 618,
  [SMALL_STATE(19)] = 652,
  [SMALL_STATE(20)] = 686,
  [SMALL_STATE(21)] = 720,
  [SMALL_STATE(22)] = 754,
  [SMALL_STATE(23)] = 788,
  [SMALL_STATE(24)] = 809,
  [SMALL_STATE(25)] = 830,
  [SMALL_STATE(26)] = 851,
  [SMALL_STATE(27)] = 872,
  [SMALL_STATE(28)] = 893,
  [SMALL_STATE(29)] = 915,
  [SMALL_STATE(30)] = 939,
  [SMALL_STATE(31)] = 959,
  [SMALL_STATE(32)] = 979,
  [SMALL_STATE(33)] = 1001,
  [SMALL_STATE(34)] = 1033,
  [SMALL_STATE(35)] = 1052,
  [SMALL_STATE(36)] = 1071,
  [SMALL_STATE(37)] = 1090,
  [SMALL_STATE(38)] = 1109,
  [SMALL_STATE(39)] = 1128,
  [SMALL_STATE(40)] = 1147,
  [SMALL_STATE(41)] = 1176,
  [SMALL_STATE(42)] = 1195,
  [SMALL_STATE(43)] = 1218,
  [SMALL_STATE(44)] = 1241,
  [SMALL_STATE(45)] = 1264,
  [SMALL_STATE(46)] = 1288,
  [SMALL_STATE(47)] = 1312,
  [SMALL_STATE(48)] = 1329,
  [SMALL_STATE(49)] = 1346,
  [SMALL_STATE(50)] = 1363,
  [SMALL_STATE(51)] = 1380,
  [SMALL_STATE(52)] = 1397,
  [SMALL_STATE(53)] = 1411,
  [SMALL_STATE(54)] = 1425,
  [SMALL_STATE(55)] = 1441,
  [SMALL_STATE(56)] = 1457,
  [SMALL_STATE(57)] = 1473,
  [SMALL_STATE(58)] = 1489,
  [SMALL_STATE(59)] = 1503,
  [SMALL_STATE(60)] = 1512,
  [SMALL_STATE(61)] = 1525,
  [SMALL_STATE(62)] = 1532,
  [SMALL_STATE(63)] = 1539,
  [SMALL_STATE(64)] = 1546,
  [SMALL_STATE(65)] = 1559,
  [SMALL_STATE(66)] = 1566,
  [SMALL_STATE(67)] = 1573,
  [SMALL_STATE(68)] = 1586,
  [SMALL_STATE(69)] = 1593,
  [SMALL_STATE(70)] = 1606,
  [SMALL_STATE(71)] = 1613,
  [SMALL_STATE(72)] = 1620,
  [SMALL_STATE(73)] = 1629,
  [SMALL_STATE(74)] = 1642,
  [SMALL_STATE(75)] = 1653,
  [SMALL_STATE(76)] = 1666,
  [SMALL_STATE(77)] = 1673,
  [SMALL_STATE(78)] = 1686,
  [SMALL_STATE(79)] = 1699,
  [SMALL_STATE(80)] = 1712,
  [SMALL_STATE(81)] = 1725,
  [SMALL_STATE(82)] = 1738,
  [SMALL_STATE(83)] = 1751,
  [SMALL_STATE(84)] = 1759,
  [SMALL_STATE(85)] = 1769,
  [SMALL_STATE(86)] = 1779,
  [SMALL_STATE(87)] = 1789,
  [SMALL_STATE(88)] = 1799,
  [SMALL_STATE(89)] = 1809,
  [SMALL_STATE(90)] = 1819,
  [SMALL_STATE(91)] = 1827,
  [SMALL_STATE(92)] = 1837,
  [SMALL_STATE(93)] = 1845,
  [SMALL_STATE(94)] = 1855,
  [SMALL_STATE(95)] = 1863,
  [SMALL_STATE(96)] = 1871,
  [SMALL_STATE(97)] = 1881,
  [SMALL_STATE(98)] = 1889,
  [SMALL_STATE(99)] = 1899,
  [SMALL_STATE(100)] = 1909,
  [SMALL_STATE(101)] = 1916,
  [SMALL_STATE(102)] = 1923,
  [SMALL_STATE(103)] = 1930,
  [SMALL_STATE(104)] = 1937,
  [SMALL_STATE(105)] = 1944,
  [SMALL_STATE(106)] = 1951,
  [SMALL_STATE(107)] = 1958,
  [SMALL_STATE(108)] = 1965,
  [SMALL_STATE(109)] = 1972,
  [SMALL_STATE(110)] = 1979,
  [SMALL_STATE(111)] = 1986,
  [SMALL_STATE(112)] = 1993,
  [SMALL_STATE(113)] = 2000,
  [SMALL_STATE(114)] = 2007,
  [SMALL_STATE(115)] = 2014,
  [SMALL_STATE(116)] = 2021,
  [SMALL_STATE(117)] = 2028,
  [SMALL_STATE(118)] = 2035,
  [SMALL_STATE(119)] = 2042,
  [SMALL_STATE(120)] = 2049,
  [SMALL_STATE(121)] = 2056,
  [SMALL_STATE(122)] = 2063,
  [SMALL_STATE(123)] = 2070,
  [SMALL_STATE(124)] = 2077,
  [SMALL_STATE(125)] = 2084,
  [SMALL_STATE(126)] = 2091,
  [SMALL_STATE(127)] = 2098,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(16),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(121),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(43),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(44),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(8),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(100),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(53),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(54),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(17),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 1),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 1),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_expression, 1),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_expression, 1),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 4),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 4),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2, .production_id = 6),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2, .production_id = 6),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_select_expression, 5),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_expression, 5),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_select_expression, 4),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_expression, 4),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_else_expression, 9, .production_id = 13),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_else_expression, 9, .production_id = 13),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_select_expression, 3),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_expression, 3),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3, .production_id = 7),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3, .production_id = 7),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 1),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_injection, 2),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_injection, 2),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_assignment, 3, .production_id = 9),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_assignment, 3, .production_id = 9),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_statement, 3, .production_id = 8),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_statement, 3, .production_id = 8),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_declaration, 4, .production_id = 10),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_declaration, 4, .production_id = 10),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, .production_id = 11),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, .production_id = 11),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(64),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(122),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(127),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2), SHIFT_REPEAT(52),
  [212] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat2, 2),
  [232] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat2, 2), SHIFT_REPEAT(57),
  [235] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat2, 2), SHIFT_REPEAT(57),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 7, .production_id = 4),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function_declaration, 7, .production_id = 5),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 1),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit_type, 2),
  [260] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(40),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [265] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_select_expression_repeat1, 2), SHIFT_REPEAT(79),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_select_expression_repeat1, 2),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function_declaration, 6, .production_id = 3),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 6, .production_id = 2),
  [274] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(89),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [279] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2), SHIFT_REPEAT(74),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, .production_id = 1),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_clause, 5, .production_id = 12),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4),
  [338] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [362] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [366] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_structured_agent(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
