#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 125
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 14
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 13

enum {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_fn = 3,
  anon_sym_COLON = 4,
  anon_sym_extern = 5,
  anon_sym_LPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_RPAREN = 8,
  anon_sym_String = 9,
  anon_sym_Boolean = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_BANG = 13,
  anon_sym_let = 14,
  anon_sym_EQ = 15,
  anon_sym_if = 16,
  anon_sym_else = 17,
  anon_sym_while = 18,
  anon_sym_return = 19,
  anon_sym_select = 20,
  anon_sym_as = 21,
  anon_sym_EQ_GT = 22,
  anon_sym_DQUOTE = 23,
  aux_sym_string_literal_token1 = 24,
  anon_sym_DQUOTE_DQUOTE_DQUOTE = 25,
  aux_sym_string_literal_token2 = 26,
  sym_escape_sequence = 27,
  anon_sym_true = 28,
  anon_sym_false = 29,
  sym_placeholder = 30,
  sym_source_file = 31,
  sym_definition = 32,
  sym_function_declaration = 33,
  sym_external_function_declaration = 34,
  sym_parameter_list = 35,
  sym_parameter = 36,
  sym_type = 37,
  sym_unit_type = 38,
  sym_block = 39,
  sym_statement = 40,
  sym_injection = 41,
  sym_let_declaration = 42,
  sym_variable_assignment = 43,
  sym_expression_statement = 44,
  sym_if_statement = 45,
  sym_while_statement = 46,
  sym_return_statement = 47,
  sym_expression = 48,
  sym_if_expression = 49,
  sym_function_call = 50,
  sym_argument_list = 51,
  sym_select_expression = 52,
  sym_select_clause = 53,
  sym_string_literal = 54,
  sym_boolean_literal = 55,
  aux_sym_source_file_repeat1 = 56,
  aux_sym_function_declaration_repeat1 = 57,
  aux_sym_parameter_list_repeat1 = 58,
  aux_sym_block_repeat1 = 59,
  aux_sym_argument_list_repeat1 = 60,
  aux_sym_select_expression_repeat1 = 61,
  aux_sym_string_literal_repeat1 = 62,
  aux_sym_string_literal_repeat2 = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_fn] = "fn",
  [anon_sym_COLON] = ":",
  [anon_sym_extern] = "extern",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_String] = "String",
  [anon_sym_Boolean] = "Boolean",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_BANG] = "!",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_return] = "return",
  [anon_sym_select] = "select",
  [anon_sym_as] = "as",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = "\"\"\"",
  [aux_sym_string_literal_token2] = "string_literal_token2",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_placeholder] = "placeholder",
  [sym_source_file] = "source_file",
  [sym_definition] = "definition",
  [sym_function_declaration] = "function_declaration",
  [sym_external_function_declaration] = "external_function_declaration",
  [sym_parameter_list] = "parameter_list",
  [sym_parameter] = "parameter",
  [sym_type] = "type",
  [sym_unit_type] = "unit_type",
  [sym_block] = "block",
  [sym_statement] = "statement",
  [sym_injection] = "injection",
  [sym_let_declaration] = "let_declaration",
  [sym_variable_assignment] = "variable_assignment",
  [sym_expression_statement] = "expression_statement",
  [sym_if_statement] = "if_statement",
  [sym_while_statement] = "while_statement",
  [sym_return_statement] = "return_statement",
  [sym_expression] = "expression",
  [sym_if_expression] = "if_expression",
  [sym_function_call] = "function_call",
  [sym_argument_list] = "argument_list",
  [sym_select_expression] = "select_expression",
  [sym_select_clause] = "select_clause",
  [sym_string_literal] = "string_literal",
  [sym_boolean_literal] = "boolean_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_declaration_repeat1] = "function_declaration_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_select_expression_repeat1] = "select_expression_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
  [aux_sym_string_literal_repeat2] = "string_literal_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_String] = anon_sym_String,
  [anon_sym_Boolean] = anon_sym_Boolean,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_select] = anon_sym_select,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = anon_sym_DQUOTE_DQUOTE_DQUOTE,
  [aux_sym_string_literal_token2] = aux_sym_string_literal_token2,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_placeholder] = sym_placeholder,
  [sym_source_file] = sym_source_file,
  [sym_definition] = sym_definition,
  [sym_function_declaration] = sym_function_declaration,
  [sym_external_function_declaration] = sym_external_function_declaration,
  [sym_parameter_list] = sym_parameter_list,
  [sym_parameter] = sym_parameter,
  [sym_type] = sym_type,
  [sym_unit_type] = sym_unit_type,
  [sym_block] = sym_block,
  [sym_statement] = sym_statement,
  [sym_injection] = sym_injection,
  [sym_let_declaration] = sym_let_declaration,
  [sym_variable_assignment] = sym_variable_assignment,
  [sym_expression_statement] = sym_expression_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_while_statement] = sym_while_statement,
  [sym_return_statement] = sym_return_statement,
  [sym_expression] = sym_expression,
  [sym_if_expression] = sym_if_expression,
  [sym_function_call] = sym_function_call,
  [sym_argument_list] = sym_argument_list,
  [sym_select_expression] = sym_select_expression,
  [sym_select_clause] = sym_select_clause,
  [sym_string_literal] = sym_string_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_declaration_repeat1] = aux_sym_function_declaration_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_select_expression_repeat1] = aux_sym_select_expression_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
  [aux_sym_string_literal_repeat2] = aux_sym_string_literal_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_String] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Boolean] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_select] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_placeholder] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_external_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_unit_type] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_injection] = {
    .visible = true,
    .named = true,
  },
  [sym_let_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_while_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_if_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_select_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_select_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_select_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_alternative = 1,
  field_arguments = 2,
  field_binding = 3,
  field_body = 4,
  field_call = 5,
  field_condition = 6,
  field_consequence = 7,
  field_function = 8,
  field_name = 9,
  field_parameters = 10,
  field_result = 11,
  field_return_type = 12,
  field_type = 13,
  field_value = 14,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_arguments] = "arguments",
  [field_binding] = "binding",
  [field_body] = "body",
  [field_call] = "call",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_function] = "function",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_result] = "result",
  [field_return_type] = "return_type",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 4},
  [3] = {.index = 6, .length = 3},
  [4] = {.index = 9, .length = 4},
  [5] = {.index = 13, .length = 3},
  [6] = {.index = 16, .length = 2},
  [7] = {.index = 18, .length = 2},
  [8] = {.index = 20, .length = 2},
  [9] = {.index = 22, .length = 2},
  [10] = {.index = 24, .length = 2},
  [11] = {.index = 26, .length = 3},
  [12] = {.index = 29, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_type, 2},
  [2] =
    {field_body, 5},
    {field_name, 1},
    {field_parameters, 2},
    {field_return_type, 4},
  [6] =
    {field_name, 2},
    {field_parameters, 3},
    {field_return_type, 5},
  [9] =
    {field_body, 6},
    {field_name, 2},
    {field_parameters, 3},
    {field_return_type, 5},
  [13] =
    {field_name, 3},
    {field_parameters, 4},
    {field_return_type, 6},
  [16] =
    {field_arguments, 1},
    {field_function, 0},
  [18] =
    {field_condition, 1},
    {field_consequence, 2},
  [20] =
    {field_body, 2},
    {field_condition, 1},
  [22] =
    {field_name, 0},
    {field_value, 2},
  [24] =
    {field_name, 1},
    {field_value, 3},
  [26] =
    {field_alternative, 4},
    {field_condition, 1},
    {field_consequence, 2},
  [29] =
    {field_binding, 2},
    {field_call, 0},
    {field_result, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 66,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 14,
  [80] = 16,
  [81] = 81,
  [82] = 82,
  [83] = 69,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 116,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      if (lookahead == '!') ADVANCE(27);
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == ')') ADVANCE(24);
      if (lookahead == ',') ADVANCE(23);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == '=') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '}') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(18)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(27);
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == '=') ADVANCE(28);
      if (lookahead == '}') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(37);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(6);
      if (lookahead == '#') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(30);
      END_STATE();
    case 9:
      if (lookahead == 'U') ADVANCE(17);
      if (lookahead == 'u') ADVANCE(13);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(41);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(41);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      if (lookahead == '!') ADVANCE(27);
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == ')') ADVANCE(24);
      if (lookahead == ',') ADVANCE(23);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == '=') ADVANCE(29);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '}') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(18)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == '"') ADVANCE(2);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE_DQUOTE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead == 'U') ADVANCE(17);
      if (lookahead == 'u') ADVANCE(13);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'B') ADVANCE(1);
      if (lookahead == 'S') ADVANCE(2);
      if (lookahead == '_') ADVANCE(3);
      if (lookahead == 'a') ADVANCE(4);
      if (lookahead == 'e') ADVANCE(5);
      if (lookahead == 'f') ADVANCE(6);
      if (lookahead == 'i') ADVANCE(7);
      if (lookahead == 'l') ADVANCE(8);
      if (lookahead == 'r') ADVANCE(9);
      if (lookahead == 's') ADVANCE(10);
      if (lookahead == 't') ADVANCE(11);
      if (lookahead == 'w') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_placeholder);
      END_STATE();
    case 4:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(16);
      if (lookahead == 'x') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 12:
      if (lookahead == 'h') ADVANCE(25);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(34);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(37);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(41);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(44);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(49);
      END_STATE();
    case 42:
      if (lookahead == 'c') ADVANCE(50);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 45:
      if (lookahead == 'a') ADVANCE(52);
      END_STATE();
    case 46:
      if (lookahead == 'g') ADVANCE(53);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 49:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(57);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_String);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_select);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_Boolean);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 5},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 5},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 7},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 1},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_String] = ACTIONS(1),
    [anon_sym_Boolean] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_select] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE_DQUOTE_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_placeholder] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(123),
    [sym_definition] = STATE(44),
    [sym_function_declaration] = STATE(64),
    [sym_external_function_declaration] = STATE(64),
    [aux_sym_source_file_repeat1] = STATE(44),
    [aux_sym_function_declaration_repeat1] = STATE(65),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_extern] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(33), 1,
      sym_placeholder,
    STATE(34), 1,
      sym_string_literal,
    STATE(40), 1,
      sym_expression,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(21), 4,
      sym_if_expression,
      sym_function_call,
      sym_select_expression,
      sym_boolean_literal,
    STATE(39), 7,
      sym_injection,
      sym_let_declaration,
      sym_variable_assignment,
      sym_expression_statement,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
  [63] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(33), 1,
      sym_placeholder,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    STATE(34), 1,
      sym_string_literal,
    STATE(40), 1,
      sym_expression,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(21), 4,
      sym_if_expression,
      sym_function_call,
      sym_select_expression,
      sym_boolean_literal,
    STATE(39), 7,
      sym_injection,
      sym_let_declaration,
      sym_variable_assignment,
      sym_expression_statement,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
  [126] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(33), 1,
      sym_placeholder,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(34), 1,
      sym_string_literal,
    STATE(40), 1,
      sym_expression,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(21), 4,
      sym_if_expression,
      sym_function_call,
      sym_select_expression,
      sym_boolean_literal,
    STATE(39), 7,
      sym_injection,
      sym_let_declaration,
      sym_variable_assignment,
      sym_expression_statement,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
  [189] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(42), 1,
      anon_sym_RBRACE,
    ACTIONS(44), 1,
      anon_sym_let,
    ACTIONS(47), 1,
      anon_sym_if,
    ACTIONS(50), 1,
      anon_sym_while,
    ACTIONS(53), 1,
      anon_sym_return,
    ACTIONS(56), 1,
      anon_sym_select,
    ACTIONS(59), 1,
      anon_sym_DQUOTE,
    ACTIONS(62), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(68), 1,
      sym_placeholder,
    STATE(34), 1,
      sym_string_literal,
    STATE(40), 1,
      sym_expression,
    ACTIONS(65), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(21), 4,
      sym_if_expression,
      sym_function_call,
      sym_select_expression,
      sym_boolean_literal,
    STATE(39), 7,
      sym_injection,
      sym_let_declaration,
      sym_variable_assignment,
      sym_expression_statement,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
  [252] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(33), 1,
      sym_placeholder,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    STATE(34), 1,
      sym_string_literal,
    STATE(40), 1,
      sym_expression,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(21), 4,
      sym_if_expression,
      sym_function_call,
      sym_select_expression,
      sym_boolean_literal,
    STATE(39), 7,
      sym_injection,
      sym_let_declaration,
      sym_variable_assignment,
      sym_expression_statement,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
  [315] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(33), 1,
      sym_placeholder,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
    ACTIONS(79), 1,
      anon_sym_if,
    STATE(37), 1,
      sym_expression,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(77), 3,
      anon_sym_let,
      anon_sym_while,
      anon_sym_return,
    STATE(21), 5,
      sym_if_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [359] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_argument_list,
    ACTIONS(85), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(81), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [388] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(87), 11,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      anon_sym_as,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [412] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(91), 11,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      anon_sym_as,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [436] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(95), 11,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      anon_sym_as,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [460] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(99), 11,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      anon_sym_as,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [484] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 6,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(103), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [508] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(107), 11,
      anon_sym_let,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [532] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    ACTIONS(111), 1,
      anon_sym_BANG,
    ACTIONS(113), 1,
      anon_sym_EQ,
    STATE(12), 1,
      sym_argument_list,
    ACTIONS(85), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(81), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [564] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(115), 11,
      anon_sym_let,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [588] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 6,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(119), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [612] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(123), 11,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      anon_sym_as,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [636] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(33), 1,
      sym_placeholder,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_if,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    STATE(95), 1,
      sym_expression,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 5,
      sym_if_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [675] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(129), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [698] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(81), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [721] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(33), 1,
      sym_placeholder,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_if,
    ACTIONS(133), 1,
      anon_sym_RPAREN,
    STATE(95), 1,
      sym_expression,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 5,
      sym_if_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [760] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(135), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [783] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(139), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [806] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(33), 1,
      sym_placeholder,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_if,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      sym_expression,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 5,
      sym_if_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [845] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(33), 1,
      sym_placeholder,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_if,
    STATE(35), 1,
      sym_expression,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 5,
      sym_if_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [881] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(33), 1,
      sym_placeholder,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_if,
    STATE(97), 1,
      sym_expression,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 5,
      sym_if_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [917] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(33), 1,
      sym_placeholder,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_if,
    STATE(95), 1,
      sym_expression,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 5,
      sym_if_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [953] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(33), 1,
      sym_placeholder,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_if,
    STATE(89), 1,
      sym_expression,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 5,
      sym_if_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [989] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(33), 1,
      sym_placeholder,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_if,
    STATE(41), 1,
      sym_expression,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 5,
      sym_if_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [1025] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(33), 1,
      sym_placeholder,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_if,
    STATE(72), 1,
      sym_expression,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 5,
      sym_if_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [1061] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(33), 1,
      sym_placeholder,
    ACTIONS(73), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_if,
    STATE(92), 1,
      sym_expression,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 5,
      sym_if_expression,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [1097] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_else,
    ACTIONS(147), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(145), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [1120] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_BANG,
    ACTIONS(85), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(81), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [1143] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(151), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [1163] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(155), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [1183] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(159), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [1203] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(163), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [1223] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(167), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [1243] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(171), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [1263] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(175), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [1283] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(129), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [1303] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(179), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_DQUOTE,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [1323] = 7,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(11), 1,
      anon_sym_extern,
    ACTIONS(183), 1,
      ts_builtin_sym_end,
    STATE(65), 1,
      aux_sym_function_declaration_repeat1,
    STATE(45), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
    STATE(64), 2,
      sym_function_declaration,
      sym_external_function_declaration,
  [1347] = 7,
    ACTIONS(185), 1,
      ts_builtin_sym_end,
    ACTIONS(187), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_fn,
    ACTIONS(193), 1,
      anon_sym_extern,
    STATE(65), 1,
      aux_sym_function_declaration_repeat1,
    STATE(45), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
    STATE(64), 2,
      sym_function_declaration,
      sym_external_function_declaration,
  [1371] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_LPAREN,
    STATE(83), 1,
      sym_unit_type,
    STATE(91), 1,
      sym_type,
    ACTIONS(196), 3,
      anon_sym_String,
      anon_sym_Boolean,
      sym_identifier,
  [1389] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_LPAREN,
    STATE(69), 1,
      sym_unit_type,
    STATE(70), 1,
      sym_type,
    ACTIONS(200), 3,
      anon_sym_String,
      anon_sym_Boolean,
      sym_identifier,
  [1407] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_LPAREN,
    STATE(83), 1,
      sym_unit_type,
    STATE(85), 1,
      sym_type,
    ACTIONS(196), 3,
      anon_sym_String,
      anon_sym_Boolean,
      sym_identifier,
  [1425] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_LPAREN,
    STATE(83), 1,
      sym_unit_type,
    STATE(86), 1,
      sym_type,
    ACTIONS(196), 3,
      anon_sym_String,
      anon_sym_Boolean,
      sym_identifier,
  [1443] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_LPAREN,
    STATE(68), 1,
      sym_type,
    STATE(69), 1,
      sym_unit_type,
    ACTIONS(200), 3,
      anon_sym_String,
      anon_sym_Boolean,
      sym_identifier,
  [1461] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym_identifier,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
    STATE(122), 1,
      sym_function_call,
    STATE(53), 2,
      sym_select_clause,
      aux_sym_select_expression_repeat1,
  [1478] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
    ACTIONS(210), 1,
      anon_sym_if,
    STATE(20), 1,
      sym_if_expression,
    STATE(42), 1,
      sym_block,
    STATE(43), 1,
      sym_if_statement,
  [1497] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      sym_identifier,
    ACTIONS(215), 1,
      anon_sym_RBRACE,
    STATE(122), 1,
      sym_function_call,
    STATE(53), 2,
      sym_select_clause,
      aux_sym_select_expression_repeat1,
  [1514] = 4,
    ACTIONS(217), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_DQUOTE,
    STATE(54), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(221), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1528] = 5,
    ACTIONS(217), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(226), 1,
      aux_sym_string_literal_token2,
    ACTIONS(228), 1,
      sym_escape_sequence,
    STATE(59), 1,
      aux_sym_string_literal_repeat2,
  [1544] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
    ACTIONS(230), 1,
      anon_sym_if,
    STATE(20), 2,
      sym_block,
      sym_if_expression,
  [1558] = 5,
    ACTIONS(217), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(234), 1,
      aux_sym_string_literal_token2,
    ACTIONS(237), 1,
      sym_escape_sequence,
    STATE(57), 1,
      aux_sym_string_literal_repeat2,
  [1574] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym_identifier,
    STATE(122), 1,
      sym_function_call,
    STATE(51), 2,
      sym_select_clause,
      aux_sym_select_expression_repeat1,
  [1588] = 5,
    ACTIONS(217), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(242), 1,
      aux_sym_string_literal_token2,
    ACTIONS(244), 1,
      sym_escape_sequence,
    STATE(57), 1,
      aux_sym_string_literal_repeat2,
  [1604] = 4,
    ACTIONS(217), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_DQUOTE,
    STATE(54), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(246), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1618] = 4,
    ACTIONS(217), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_DQUOTE,
    STATE(60), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(248), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1632] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_argument_list_repeat1,
  [1645] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_identifier,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
    STATE(94), 1,
      sym_parameter,
  [1658] = 1,
    ACTIONS(258), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1665] = 4,
    ACTIONS(260), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_fn,
    ACTIONS(264), 1,
      anon_sym_extern,
    STATE(77), 1,
      aux_sym_function_declaration_repeat1,
  [1678] = 1,
    ACTIONS(266), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1685] = 1,
    ACTIONS(268), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1692] = 1,
    ACTIONS(270), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1699] = 1,
    ACTIONS(272), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1706] = 1,
    ACTIONS(274), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1713] = 1,
    ACTIONS(276), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1720] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_COMMA,
    ACTIONS(278), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1731] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_COMMA,
    ACTIONS(285), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_argument_list_repeat1,
  [1744] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [1753] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_COMMA,
    ACTIONS(290), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      aux_sym_parameter_list_repeat1,
  [1766] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_identifier,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
    STATE(94), 1,
      sym_parameter,
  [1779] = 3,
    ACTIONS(294), 1,
      sym_comment,
    STATE(77), 1,
      aux_sym_function_declaration_repeat1,
    ACTIONS(297), 2,
      anon_sym_fn,
      anon_sym_extern,
  [1790] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_identifier,
    ACTIONS(299), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      sym_parameter,
  [1803] = 1,
    ACTIONS(109), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1810] = 1,
    ACTIONS(117), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1817] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_RPAREN,
    ACTIONS(301), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_argument_list_repeat1,
  [1830] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_COMMA,
    ACTIONS(305), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      aux_sym_parameter_list_repeat1,
  [1843] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [1852] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
    ACTIONS(307), 1,
      anon_sym_COMMA,
    STATE(75), 1,
      aux_sym_parameter_list_repeat1,
  [1865] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1873] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_LBRACE,
    STATE(71), 1,
      sym_block,
  [1883] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_LPAREN,
    STATE(107), 1,
      sym_parameter_list,
  [1893] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_argument_list,
  [1903] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
    STATE(33), 1,
      sym_block,
  [1913] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1921] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_LBRACE,
    STATE(67), 1,
      sym_block,
  [1931] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_block,
  [1941] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_LPAREN,
    STATE(106), 1,
      sym_parameter_list,
  [1951] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1959] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1967] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_LPAREN,
    STATE(100), 1,
      sym_parameter_list,
  [1977] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
    STATE(110), 1,
      sym_block,
  [1987] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_identifier,
    STATE(94), 1,
      sym_parameter,
  [1997] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_LPAREN,
    STATE(105), 1,
      sym_parameter_list,
  [2007] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      anon_sym_COLON,
  [2014] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      sym_identifier,
  [2021] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_COLON,
  [2028] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_COLON,
  [2035] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      sym_identifier,
  [2042] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      anon_sym_COLON,
  [2049] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_COLON,
  [2056] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      anon_sym_COLON,
  [2063] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_EQ_GT,
  [2070] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      anon_sym_COLON,
  [2077] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      anon_sym_else,
  [2084] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      anon_sym_fn,
  [2091] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_COLON,
  [2098] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      sym_identifier,
  [2105] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      sym_identifier,
  [2112] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      sym_identifier,
  [2119] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_RPAREN,
  [2126] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      anon_sym_RPAREN,
  [2133] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_COLON,
  [2140] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      anon_sym_EQ,
  [2147] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      sym_identifier,
  [2154] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_LBRACE,
  [2161] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      anon_sym_as,
  [2168] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 1,
      ts_builtin_sym_end,
  [2175] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      anon_sym_fn,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 63,
  [SMALL_STATE(4)] = 126,
  [SMALL_STATE(5)] = 189,
  [SMALL_STATE(6)] = 252,
  [SMALL_STATE(7)] = 315,
  [SMALL_STATE(8)] = 359,
  [SMALL_STATE(9)] = 388,
  [SMALL_STATE(10)] = 412,
  [SMALL_STATE(11)] = 436,
  [SMALL_STATE(12)] = 460,
  [SMALL_STATE(13)] = 484,
  [SMALL_STATE(14)] = 508,
  [SMALL_STATE(15)] = 532,
  [SMALL_STATE(16)] = 564,
  [SMALL_STATE(17)] = 588,
  [SMALL_STATE(18)] = 612,
  [SMALL_STATE(19)] = 636,
  [SMALL_STATE(20)] = 675,
  [SMALL_STATE(21)] = 698,
  [SMALL_STATE(22)] = 721,
  [SMALL_STATE(23)] = 760,
  [SMALL_STATE(24)] = 783,
  [SMALL_STATE(25)] = 806,
  [SMALL_STATE(26)] = 845,
  [SMALL_STATE(27)] = 881,
  [SMALL_STATE(28)] = 917,
  [SMALL_STATE(29)] = 953,
  [SMALL_STATE(30)] = 989,
  [SMALL_STATE(31)] = 1025,
  [SMALL_STATE(32)] = 1061,
  [SMALL_STATE(33)] = 1097,
  [SMALL_STATE(34)] = 1120,
  [SMALL_STATE(35)] = 1143,
  [SMALL_STATE(36)] = 1163,
  [SMALL_STATE(37)] = 1183,
  [SMALL_STATE(38)] = 1203,
  [SMALL_STATE(39)] = 1223,
  [SMALL_STATE(40)] = 1243,
  [SMALL_STATE(41)] = 1263,
  [SMALL_STATE(42)] = 1283,
  [SMALL_STATE(43)] = 1303,
  [SMALL_STATE(44)] = 1323,
  [SMALL_STATE(45)] = 1347,
  [SMALL_STATE(46)] = 1371,
  [SMALL_STATE(47)] = 1389,
  [SMALL_STATE(48)] = 1407,
  [SMALL_STATE(49)] = 1425,
  [SMALL_STATE(50)] = 1443,
  [SMALL_STATE(51)] = 1461,
  [SMALL_STATE(52)] = 1478,
  [SMALL_STATE(53)] = 1497,
  [SMALL_STATE(54)] = 1514,
  [SMALL_STATE(55)] = 1528,
  [SMALL_STATE(56)] = 1544,
  [SMALL_STATE(57)] = 1558,
  [SMALL_STATE(58)] = 1574,
  [SMALL_STATE(59)] = 1588,
  [SMALL_STATE(60)] = 1604,
  [SMALL_STATE(61)] = 1618,
  [SMALL_STATE(62)] = 1632,
  [SMALL_STATE(63)] = 1645,
  [SMALL_STATE(64)] = 1658,
  [SMALL_STATE(65)] = 1665,
  [SMALL_STATE(66)] = 1678,
  [SMALL_STATE(67)] = 1685,
  [SMALL_STATE(68)] = 1692,
  [SMALL_STATE(69)] = 1699,
  [SMALL_STATE(70)] = 1706,
  [SMALL_STATE(71)] = 1713,
  [SMALL_STATE(72)] = 1720,
  [SMALL_STATE(73)] = 1731,
  [SMALL_STATE(74)] = 1744,
  [SMALL_STATE(75)] = 1753,
  [SMALL_STATE(76)] = 1766,
  [SMALL_STATE(77)] = 1779,
  [SMALL_STATE(78)] = 1790,
  [SMALL_STATE(79)] = 1803,
  [SMALL_STATE(80)] = 1810,
  [SMALL_STATE(81)] = 1817,
  [SMALL_STATE(82)] = 1830,
  [SMALL_STATE(83)] = 1843,
  [SMALL_STATE(84)] = 1852,
  [SMALL_STATE(85)] = 1865,
  [SMALL_STATE(86)] = 1873,
  [SMALL_STATE(87)] = 1883,
  [SMALL_STATE(88)] = 1893,
  [SMALL_STATE(89)] = 1903,
  [SMALL_STATE(90)] = 1913,
  [SMALL_STATE(91)] = 1921,
  [SMALL_STATE(92)] = 1931,
  [SMALL_STATE(93)] = 1941,
  [SMALL_STATE(94)] = 1951,
  [SMALL_STATE(95)] = 1959,
  [SMALL_STATE(96)] = 1967,
  [SMALL_STATE(97)] = 1977,
  [SMALL_STATE(98)] = 1987,
  [SMALL_STATE(99)] = 1997,
  [SMALL_STATE(100)] = 2007,
  [SMALL_STATE(101)] = 2014,
  [SMALL_STATE(102)] = 2021,
  [SMALL_STATE(103)] = 2028,
  [SMALL_STATE(104)] = 2035,
  [SMALL_STATE(105)] = 2042,
  [SMALL_STATE(106)] = 2049,
  [SMALL_STATE(107)] = 2056,
  [SMALL_STATE(108)] = 2063,
  [SMALL_STATE(109)] = 2070,
  [SMALL_STATE(110)] = 2077,
  [SMALL_STATE(111)] = 2084,
  [SMALL_STATE(112)] = 2091,
  [SMALL_STATE(113)] = 2098,
  [SMALL_STATE(114)] = 2105,
  [SMALL_STATE(115)] = 2112,
  [SMALL_STATE(116)] = 2119,
  [SMALL_STATE(117)] = 2126,
  [SMALL_STATE(118)] = 2133,
  [SMALL_STATE(119)] = 2140,
  [SMALL_STATE(120)] = 2147,
  [SMALL_STATE(121)] = 2154,
  [SMALL_STATE(122)] = 2161,
  [SMALL_STATE(123)] = 2168,
  [SMALL_STATE(124)] = 2175,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(15),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(115),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(29),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(32),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(7),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(121),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(61),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(55),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(23),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(21),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 1),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 1),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 4),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 4),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2, .production_id = 6),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2, .production_id = 6),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 5),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 5),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 5, .production_id = 11),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 5, .production_id = 11),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_select_expression, 4),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_expression, 4),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3, .production_id = 7),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3, .production_id = 7),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_assignment, 3, .production_id = 9),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_assignment, 3, .production_id = 9),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_injection, 2),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_injection, 2),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_statement, 3, .production_id = 8),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_statement, 3, .production_id = 8),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 1),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_declaration, 4, .production_id = 10),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_declaration, 4, .production_id = 10),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, .production_id = 11),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, .production_id = 11),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(65),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(120),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(124),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_select_expression_repeat1, 2), SHIFT_REPEAT(88),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_select_expression_repeat1, 2),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2), SHIFT_REPEAT(54),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat2, 2),
  [234] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat2, 2), SHIFT_REPEAT(57),
  [237] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat2, 2), SHIFT_REPEAT(57),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 1),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit_type, 2),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 7, .production_id = 4),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function_declaration, 7, .production_id = 5),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function_declaration, 6, .production_id = 3),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 6, .production_id = 2),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_clause, 5, .production_id = 12),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [282] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(28),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [287] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(98),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [294] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2), SHIFT_REPEAT(77),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, .production_id = 1),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_clause, 6, .production_id = 12),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [341] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 5),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [363] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_structured_agent(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
