#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 114
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 61
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 12

enum {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_fn = 3,
  anon_sym_COLON = 4,
  anon_sym_extern = 5,
  anon_sym_LPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_RPAREN = 8,
  anon_sym_String = 9,
  anon_sym_Boolean = 10,
  anon_sym_i32 = 11,
  anon_sym_Context = 12,
  anon_sym_LBRACE = 13,
  anon_sym_RBRACE = 14,
  anon_sym_BANG = 15,
  anon_sym_let = 16,
  anon_sym_EQ = 17,
  anon_sym_if = 18,
  anon_sym_while = 19,
  anon_sym_return = 20,
  anon_sym_select = 21,
  anon_sym_as = 22,
  anon_sym_EQ_GT = 23,
  anon_sym_DQUOTE = 24,
  aux_sym_string_literal_token1 = 25,
  sym_escape_sequence = 26,
  anon_sym_true = 27,
  anon_sym_false = 28,
  sym_placeholder = 29,
  sym_source_file = 30,
  sym_definition = 31,
  sym_function_declaration = 32,
  sym_external_function_declaration = 33,
  sym_parameter_list = 34,
  sym_parameter = 35,
  sym_type = 36,
  sym_unit_type = 37,
  sym_block = 38,
  sym_statement = 39,
  sym_injection = 40,
  sym_let_declaration = 41,
  sym_variable_assignment = 42,
  sym_expression_statement = 43,
  sym_if_statement = 44,
  sym_while_statement = 45,
  sym_return_statement = 46,
  sym_expression = 47,
  sym_function_call = 48,
  sym_argument_list = 49,
  sym_select_expression = 50,
  sym_select_clause = 51,
  sym_string_literal = 52,
  sym_boolean_literal = 53,
  aux_sym_source_file_repeat1 = 54,
  aux_sym_function_declaration_repeat1 = 55,
  aux_sym_parameter_list_repeat1 = 56,
  aux_sym_block_repeat1 = 57,
  aux_sym_argument_list_repeat1 = 58,
  aux_sym_select_expression_repeat1 = 59,
  aux_sym_string_literal_repeat1 = 60,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_fn] = "fn",
  [anon_sym_COLON] = ":",
  [anon_sym_extern] = "extern",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_String] = "String",
  [anon_sym_Boolean] = "Boolean",
  [anon_sym_i32] = "i32",
  [anon_sym_Context] = "Context",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_BANG] = "!",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_if] = "if",
  [anon_sym_while] = "while",
  [anon_sym_return] = "return",
  [anon_sym_select] = "select",
  [anon_sym_as] = "as",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_placeholder] = "placeholder",
  [sym_source_file] = "source_file",
  [sym_definition] = "definition",
  [sym_function_declaration] = "function_declaration",
  [sym_external_function_declaration] = "external_function_declaration",
  [sym_parameter_list] = "parameter_list",
  [sym_parameter] = "parameter",
  [sym_type] = "type",
  [sym_unit_type] = "unit_type",
  [sym_block] = "block",
  [sym_statement] = "statement",
  [sym_injection] = "injection",
  [sym_let_declaration] = "let_declaration",
  [sym_variable_assignment] = "variable_assignment",
  [sym_expression_statement] = "expression_statement",
  [sym_if_statement] = "if_statement",
  [sym_while_statement] = "while_statement",
  [sym_return_statement] = "return_statement",
  [sym_expression] = "expression",
  [sym_function_call] = "function_call",
  [sym_argument_list] = "argument_list",
  [sym_select_expression] = "select_expression",
  [sym_select_clause] = "select_clause",
  [sym_string_literal] = "string_literal",
  [sym_boolean_literal] = "boolean_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_declaration_repeat1] = "function_declaration_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_select_expression_repeat1] = "select_expression_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_String] = anon_sym_String,
  [anon_sym_Boolean] = anon_sym_Boolean,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_Context] = anon_sym_Context,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_select] = anon_sym_select,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_placeholder] = sym_placeholder,
  [sym_source_file] = sym_source_file,
  [sym_definition] = sym_definition,
  [sym_function_declaration] = sym_function_declaration,
  [sym_external_function_declaration] = sym_external_function_declaration,
  [sym_parameter_list] = sym_parameter_list,
  [sym_parameter] = sym_parameter,
  [sym_type] = sym_type,
  [sym_unit_type] = sym_unit_type,
  [sym_block] = sym_block,
  [sym_statement] = sym_statement,
  [sym_injection] = sym_injection,
  [sym_let_declaration] = sym_let_declaration,
  [sym_variable_assignment] = sym_variable_assignment,
  [sym_expression_statement] = sym_expression_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_while_statement] = sym_while_statement,
  [sym_return_statement] = sym_return_statement,
  [sym_expression] = sym_expression,
  [sym_function_call] = sym_function_call,
  [sym_argument_list] = sym_argument_list,
  [sym_select_expression] = sym_select_expression,
  [sym_select_clause] = sym_select_clause,
  [sym_string_literal] = sym_string_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_declaration_repeat1] = aux_sym_function_declaration_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_select_expression_repeat1] = aux_sym_select_expression_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_String] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Boolean] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Context] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_select] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_placeholder] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_external_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_unit_type] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_injection] = {
    .visible = true,
    .named = true,
  },
  [sym_let_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_while_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_select_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_select_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_select_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_arguments = 1,
  field_binding = 2,
  field_body = 3,
  field_call = 4,
  field_condition = 5,
  field_consequence = 6,
  field_function = 7,
  field_name = 8,
  field_parameters = 9,
  field_result = 10,
  field_return_type = 11,
  field_type = 12,
  field_value = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_binding] = "binding",
  [field_body] = "body",
  [field_call] = "call",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_function] = "function",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_result] = "result",
  [field_return_type] = "return_type",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 4},
  [3] = {.index = 6, .length = 3},
  [4] = {.index = 9, .length = 4},
  [5] = {.index = 13, .length = 3},
  [6] = {.index = 16, .length = 2},
  [7] = {.index = 18, .length = 2},
  [8] = {.index = 20, .length = 2},
  [9] = {.index = 22, .length = 2},
  [10] = {.index = 24, .length = 2},
  [11] = {.index = 26, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
    {field_type, 2},
  [2] =
    {field_body, 5},
    {field_name, 1},
    {field_parameters, 2},
    {field_return_type, 4},
  [6] =
    {field_name, 2},
    {field_parameters, 3},
    {field_return_type, 5},
  [9] =
    {field_body, 6},
    {field_name, 2},
    {field_parameters, 3},
    {field_return_type, 5},
  [13] =
    {field_name, 3},
    {field_parameters, 4},
    {field_return_type, 6},
  [16] =
    {field_arguments, 1},
    {field_function, 0},
  [18] =
    {field_condition, 1},
    {field_consequence, 2},
  [20] =
    {field_body, 2},
    {field_condition, 1},
  [22] =
    {field_name, 0},
    {field_value, 2},
  [24] =
    {field_name, 1},
    {field_value, 3},
  [26] =
    {field_binding, 2},
    {field_call, 0},
    {field_result, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 39,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 66,
  [72] = 58,
  [73] = 28,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 95,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '!') ADVANCE(23);
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == ')') ADVANCE(20);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead == '}') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(14)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(23);
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == '=') ADVANCE(24);
      if (lookahead == '}') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '#') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '=') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(26);
      END_STATE();
    case 5:
      if (lookahead == 'U') ADVANCE(13);
      if (lookahead == 'u') ADVANCE(9);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(32);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(6);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(7);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(8);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '!') ADVANCE(23);
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == ')') ADVANCE(20);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead == '}') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(14)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '#') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'B') ADVANCE(1);
      if (lookahead == 'C') ADVANCE(2);
      if (lookahead == 'S') ADVANCE(3);
      if (lookahead == '_') ADVANCE(4);
      if (lookahead == 'a') ADVANCE(5);
      if (lookahead == 'e') ADVANCE(6);
      if (lookahead == 'f') ADVANCE(7);
      if (lookahead == 'i') ADVANCE(8);
      if (lookahead == 'l') ADVANCE(9);
      if (lookahead == 'r') ADVANCE(10);
      if (lookahead == 's') ADVANCE(11);
      if (lookahead == 't') ADVANCE(12);
      if (lookahead == 'w') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_placeholder);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'x') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(19);
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == '3') ADVANCE(21);
      if (lookahead == 'f') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(27);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 21:
      if (lookahead == '2') ADVANCE(33);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(41);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(43);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(44);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(50);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(51);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 44:
      if (lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 45:
      if (lookahead == 'c') ADVANCE(54);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 48:
      if (lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 49:
      if (lookahead == 'x') ADVANCE(57);
      END_STATE();
    case 50:
      if (lookahead == 'g') ADVANCE(58);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(59);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 53:
      if (lookahead == 'n') ADVANCE(60);
      END_STATE();
    case 54:
      if (lookahead == 't') ADVANCE(61);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 56:
      if (lookahead == 'n') ADVANCE(62);
      END_STATE();
    case 57:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_String);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_select);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_Boolean);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_Context);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 3},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_String] = ACTIONS(1),
    [anon_sym_Boolean] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_Context] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_select] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_placeholder] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(112),
    [sym_definition] = STATE(44),
    [sym_function_declaration] = STATE(55),
    [sym_external_function_declaration] = STATE(55),
    [aux_sym_source_file_repeat1] = STATE(44),
    [aux_sym_function_declaration_repeat1] = STATE(57),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_extern] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      sym_placeholder,
    STATE(21), 1,
      sym_string_literal,
    STATE(36), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(6), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(16), 3,
      sym_function_call,
      sym_select_expression,
      sym_boolean_literal,
    STATE(37), 7,
      sym_injection,
      sym_let_declaration,
      sym_variable_assignment,
      sym_expression_statement,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
  [59] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      sym_placeholder,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      sym_string_literal,
    STATE(36), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(16), 3,
      sym_function_call,
      sym_select_expression,
      sym_boolean_literal,
    STATE(37), 7,
      sym_injection,
      sym_let_declaration,
      sym_variable_assignment,
      sym_expression_statement,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
  [118] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      sym_placeholder,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      sym_string_literal,
    STATE(36), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(16), 3,
      sym_function_call,
      sym_select_expression,
      sym_boolean_literal,
    STATE(37), 7,
      sym_injection,
      sym_let_declaration,
      sym_variable_assignment,
      sym_expression_statement,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
  [177] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_while,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      sym_placeholder,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      sym_string_literal,
    STATE(36), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(6), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(16), 3,
      sym_function_call,
      sym_select_expression,
      sym_boolean_literal,
    STATE(37), 7,
      sym_injection,
      sym_let_declaration,
      sym_variable_assignment,
      sym_expression_statement,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
  [236] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(42), 1,
      anon_sym_RBRACE,
    ACTIONS(44), 1,
      anon_sym_let,
    ACTIONS(47), 1,
      anon_sym_if,
    ACTIONS(50), 1,
      anon_sym_while,
    ACTIONS(53), 1,
      anon_sym_return,
    ACTIONS(56), 1,
      anon_sym_select,
    ACTIONS(59), 1,
      anon_sym_DQUOTE,
    ACTIONS(65), 1,
      sym_placeholder,
    STATE(21), 1,
      sym_string_literal,
    STATE(36), 1,
      sym_expression,
    ACTIONS(62), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(6), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(16), 3,
      sym_function_call,
      sym_select_expression,
      sym_boolean_literal,
    STATE(37), 7,
      sym_injection,
      sym_let_declaration,
      sym_variable_assignment,
      sym_expression_statement,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
  [295] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    STATE(13), 1,
      sym_argument_list,
    ACTIONS(72), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(68), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [323] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_BANG,
    ACTIONS(76), 1,
      anon_sym_EQ,
    STATE(13), 1,
      sym_argument_list,
    ACTIONS(72), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(68), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [354] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(78), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      anon_sym_as,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [377] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(82), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      anon_sym_as,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [400] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(86), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      anon_sym_as,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [423] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(90), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      anon_sym_as,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [446] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(94), 10,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      anon_sym_as,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [469] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 6,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DQUOTE,
    ACTIONS(98), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [492] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 6,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BANG,
      anon_sym_DQUOTE,
    ACTIONS(102), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [515] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(68), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [537] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(106), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [559] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(110), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [581] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      sym_placeholder,
    ACTIONS(114), 1,
      sym_identifier,
    ACTIONS(116), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(16), 4,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [613] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      sym_placeholder,
    ACTIONS(114), 1,
      sym_identifier,
    ACTIONS(118), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(16), 4,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [645] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_BANG,
    ACTIONS(72), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(68), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [667] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      sym_placeholder,
    ACTIONS(114), 1,
      sym_identifier,
    ACTIONS(120), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(16), 4,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [699] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(122), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [718] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(126), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [737] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      sym_placeholder,
    ACTIONS(114), 1,
      sym_identifier,
    STATE(84), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(16), 4,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [766] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(130), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [785] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      sym_placeholder,
    ACTIONS(114), 1,
      sym_identifier,
    STATE(30), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(16), 4,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [814] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(134), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [833] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      sym_placeholder,
    ACTIONS(114), 1,
      sym_identifier,
    STATE(59), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(16), 4,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [862] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(138), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [881] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      sym_placeholder,
    ACTIONS(114), 1,
      sym_identifier,
    STATE(23), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(16), 4,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [910] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(142), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [929] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(146), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [948] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      sym_placeholder,
    ACTIONS(114), 1,
      sym_identifier,
    STATE(76), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(16), 4,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [977] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      sym_placeholder,
    ACTIONS(114), 1,
      sym_identifier,
    STATE(77), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(16), 4,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [1006] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(150), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [1025] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(154), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [1044] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_select,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(31), 1,
      sym_placeholder,
    ACTIONS(114), 1,
      sym_identifier,
    STATE(33), 1,
      sym_expression,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(16), 4,
      sym_function_call,
      sym_select_expression,
      sym_string_literal,
      sym_boolean_literal,
  [1073] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(158), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_select,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_placeholder,
  [1092] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
    STATE(72), 1,
      sym_unit_type,
    STATE(86), 1,
      sym_type,
    ACTIONS(162), 5,
      anon_sym_String,
      anon_sym_Boolean,
      anon_sym_i32,
      anon_sym_Context,
      sym_identifier,
  [1112] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
    STATE(72), 1,
      sym_unit_type,
    STATE(83), 1,
      sym_type,
    ACTIONS(162), 5,
      anon_sym_String,
      anon_sym_Boolean,
      anon_sym_i32,
      anon_sym_Context,
      sym_identifier,
  [1132] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    STATE(58), 1,
      sym_unit_type,
    STATE(68), 1,
      sym_type,
    ACTIONS(166), 5,
      anon_sym_String,
      anon_sym_Boolean,
      anon_sym_i32,
      anon_sym_Context,
      sym_identifier,
  [1152] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_LPAREN,
    STATE(72), 1,
      sym_unit_type,
    STATE(89), 1,
      sym_type,
    ACTIONS(162), 5,
      anon_sym_String,
      anon_sym_Boolean,
      anon_sym_i32,
      anon_sym_Context,
      sym_identifier,
  [1172] = 7,
    ACTIONS(7), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(11), 1,
      anon_sym_extern,
    ACTIONS(170), 1,
      ts_builtin_sym_end,
    STATE(57), 1,
      aux_sym_function_declaration_repeat1,
    STATE(45), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
    STATE(55), 2,
      sym_function_declaration,
      sym_external_function_declaration,
  [1196] = 7,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
    ACTIONS(174), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_fn,
    ACTIONS(180), 1,
      anon_sym_extern,
    STATE(57), 1,
      aux_sym_function_declaration_repeat1,
    STATE(45), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
    STATE(55), 2,
      sym_function_declaration,
      sym_external_function_declaration,
  [1220] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    STATE(58), 1,
      sym_unit_type,
    STATE(65), 1,
      sym_type,
    ACTIONS(166), 5,
      anon_sym_String,
      anon_sym_Boolean,
      anon_sym_i32,
      anon_sym_Context,
      sym_identifier,
  [1240] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      sym_identifier,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    STATE(100), 1,
      sym_function_call,
    STATE(48), 2,
      sym_select_clause,
      aux_sym_select_expression_repeat1,
  [1257] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      sym_identifier,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    STATE(100), 1,
      sym_function_call,
    STATE(48), 2,
      sym_select_clause,
      aux_sym_select_expression_repeat1,
  [1274] = 4,
    ACTIONS(192), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_DQUOTE,
    STATE(51), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(196), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1288] = 4,
    ACTIONS(192), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_DQUOTE,
    STATE(50), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(200), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1302] = 4,
    ACTIONS(192), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_DQUOTE,
    STATE(50), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(205), 2,
      aux_sym_string_literal_token1,
      sym_escape_sequence,
  [1316] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      sym_identifier,
    STATE(100), 1,
      sym_function_call,
    STATE(47), 2,
      sym_select_clause,
      aux_sym_select_expression_repeat1,
  [1330] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      anon_sym_RPAREN,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_argument_list_repeat1,
  [1343] = 1,
    ACTIONS(209), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1350] = 1,
    ACTIONS(211), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1357] = 1,
    ACTIONS(160), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1364] = 4,
    ACTIONS(213), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_fn,
    ACTIONS(217), 1,
      anon_sym_extern,
    STATE(63), 1,
      aux_sym_function_declaration_repeat1,
  [1377] = 1,
    ACTIONS(219), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1384] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(221), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1395] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      aux_sym_parameter_list_repeat1,
  [1408] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      sym_identifier,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      sym_parameter,
  [1421] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_COMMA,
    ACTIONS(237), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      aux_sym_argument_list_repeat1,
  [1434] = 3,
    ACTIONS(239), 1,
      sym_comment,
    STATE(63), 1,
      aux_sym_function_declaration_repeat1,
    ACTIONS(242), 2,
      anon_sym_fn,
      anon_sym_extern,
  [1445] = 1,
    ACTIONS(244), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1452] = 1,
    ACTIONS(246), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1459] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [1468] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      sym_identifier,
    ACTIONS(250), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      sym_parameter,
  [1481] = 1,
    ACTIONS(252), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1488] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_COMMA,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      aux_sym_argument_list_repeat1,
  [1501] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_COMMA,
    ACTIONS(260), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      aux_sym_parameter_list_repeat1,
  [1514] = 1,
    ACTIONS(248), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1521] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [1530] = 1,
    ACTIONS(136), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_extern,
  [1537] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      aux_sym_parameter_list_repeat1,
  [1550] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      sym_identifier,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      sym_parameter,
  [1563] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1571] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      sym_block,
  [1581] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1589] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_LPAREN,
    STATE(93), 1,
      sym_parameter_list,
  [1599] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1607] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_LPAREN,
    STATE(94), 1,
      sym_parameter_list,
  [1617] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    STATE(13), 1,
      sym_argument_list,
  [1627] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1635] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_LBRACE,
    STATE(24), 1,
      sym_block,
  [1645] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      sym_identifier,
    STATE(80), 1,
      sym_parameter,
  [1655] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_LBRACE,
    STATE(54), 1,
      sym_block,
  [1665] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_LPAREN,
    STATE(104), 1,
      sym_parameter_list,
  [1675] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_LPAREN,
    STATE(105), 1,
      sym_parameter_list,
  [1685] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_LBRACE,
    STATE(64), 1,
      sym_block,
  [1695] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      sym_identifier,
  [1702] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_COLON,
  [1709] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_COLON,
  [1716] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_COLON,
  [1723] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_COLON,
  [1730] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
  [1737] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_RPAREN,
  [1744] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_EQ_GT,
  [1751] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_EQ,
  [1758] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      anon_sym_COLON,
  [1765] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_as,
  [1772] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      sym_identifier,
  [1779] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      sym_identifier,
  [1786] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      sym_identifier,
  [1793] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_COLON,
  [1800] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_COLON,
  [1807] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      anon_sym_COLON,
  [1814] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      sym_identifier,
  [1821] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      anon_sym_COLON,
  [1828] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_LBRACE,
  [1835] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      sym_identifier,
  [1842] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 1,
      anon_sym_fn,
  [1849] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      ts_builtin_sym_end,
  [1856] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      anon_sym_fn,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 59,
  [SMALL_STATE(4)] = 118,
  [SMALL_STATE(5)] = 177,
  [SMALL_STATE(6)] = 236,
  [SMALL_STATE(7)] = 295,
  [SMALL_STATE(8)] = 323,
  [SMALL_STATE(9)] = 354,
  [SMALL_STATE(10)] = 377,
  [SMALL_STATE(11)] = 400,
  [SMALL_STATE(12)] = 423,
  [SMALL_STATE(13)] = 446,
  [SMALL_STATE(14)] = 469,
  [SMALL_STATE(15)] = 492,
  [SMALL_STATE(16)] = 515,
  [SMALL_STATE(17)] = 537,
  [SMALL_STATE(18)] = 559,
  [SMALL_STATE(19)] = 581,
  [SMALL_STATE(20)] = 613,
  [SMALL_STATE(21)] = 645,
  [SMALL_STATE(22)] = 667,
  [SMALL_STATE(23)] = 699,
  [SMALL_STATE(24)] = 718,
  [SMALL_STATE(25)] = 737,
  [SMALL_STATE(26)] = 766,
  [SMALL_STATE(27)] = 785,
  [SMALL_STATE(28)] = 814,
  [SMALL_STATE(29)] = 833,
  [SMALL_STATE(30)] = 862,
  [SMALL_STATE(31)] = 881,
  [SMALL_STATE(32)] = 910,
  [SMALL_STATE(33)] = 929,
  [SMALL_STATE(34)] = 948,
  [SMALL_STATE(35)] = 977,
  [SMALL_STATE(36)] = 1006,
  [SMALL_STATE(37)] = 1025,
  [SMALL_STATE(38)] = 1044,
  [SMALL_STATE(39)] = 1073,
  [SMALL_STATE(40)] = 1092,
  [SMALL_STATE(41)] = 1112,
  [SMALL_STATE(42)] = 1132,
  [SMALL_STATE(43)] = 1152,
  [SMALL_STATE(44)] = 1172,
  [SMALL_STATE(45)] = 1196,
  [SMALL_STATE(46)] = 1220,
  [SMALL_STATE(47)] = 1240,
  [SMALL_STATE(48)] = 1257,
  [SMALL_STATE(49)] = 1274,
  [SMALL_STATE(50)] = 1288,
  [SMALL_STATE(51)] = 1302,
  [SMALL_STATE(52)] = 1316,
  [SMALL_STATE(53)] = 1330,
  [SMALL_STATE(54)] = 1343,
  [SMALL_STATE(55)] = 1350,
  [SMALL_STATE(56)] = 1357,
  [SMALL_STATE(57)] = 1364,
  [SMALL_STATE(58)] = 1377,
  [SMALL_STATE(59)] = 1384,
  [SMALL_STATE(60)] = 1395,
  [SMALL_STATE(61)] = 1408,
  [SMALL_STATE(62)] = 1421,
  [SMALL_STATE(63)] = 1434,
  [SMALL_STATE(64)] = 1445,
  [SMALL_STATE(65)] = 1452,
  [SMALL_STATE(66)] = 1459,
  [SMALL_STATE(67)] = 1468,
  [SMALL_STATE(68)] = 1481,
  [SMALL_STATE(69)] = 1488,
  [SMALL_STATE(70)] = 1501,
  [SMALL_STATE(71)] = 1514,
  [SMALL_STATE(72)] = 1521,
  [SMALL_STATE(73)] = 1530,
  [SMALL_STATE(74)] = 1537,
  [SMALL_STATE(75)] = 1550,
  [SMALL_STATE(76)] = 1563,
  [SMALL_STATE(77)] = 1571,
  [SMALL_STATE(78)] = 1581,
  [SMALL_STATE(79)] = 1589,
  [SMALL_STATE(80)] = 1599,
  [SMALL_STATE(81)] = 1607,
  [SMALL_STATE(82)] = 1617,
  [SMALL_STATE(83)] = 1627,
  [SMALL_STATE(84)] = 1635,
  [SMALL_STATE(85)] = 1645,
  [SMALL_STATE(86)] = 1655,
  [SMALL_STATE(87)] = 1665,
  [SMALL_STATE(88)] = 1675,
  [SMALL_STATE(89)] = 1685,
  [SMALL_STATE(90)] = 1695,
  [SMALL_STATE(91)] = 1702,
  [SMALL_STATE(92)] = 1709,
  [SMALL_STATE(93)] = 1716,
  [SMALL_STATE(94)] = 1723,
  [SMALL_STATE(95)] = 1730,
  [SMALL_STATE(96)] = 1737,
  [SMALL_STATE(97)] = 1744,
  [SMALL_STATE(98)] = 1751,
  [SMALL_STATE(99)] = 1758,
  [SMALL_STATE(100)] = 1765,
  [SMALL_STATE(101)] = 1772,
  [SMALL_STATE(102)] = 1779,
  [SMALL_STATE(103)] = 1786,
  [SMALL_STATE(104)] = 1793,
  [SMALL_STATE(105)] = 1800,
  [SMALL_STATE(106)] = 1807,
  [SMALL_STATE(107)] = 1814,
  [SMALL_STATE(108)] = 1821,
  [SMALL_STATE(109)] = 1828,
  [SMALL_STATE(110)] = 1835,
  [SMALL_STATE(111)] = 1842,
  [SMALL_STATE(112)] = 1849,
  [SMALL_STATE(113)] = 1856,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(8),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(110),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(35),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(25),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(38),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(109),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(49),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(17),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(16),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 5),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 5),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 4),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 4),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2, .production_id = 6),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2, .production_id = 6),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_select_expression, 4),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_expression, 4),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_assignment, 3, .production_id = 9),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_assignment, 3, .production_id = 9),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_statement, 3, .production_id = 8),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_statement, 3, .production_id = 8),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3, .production_id = 7),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3, .production_id = 7),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_declaration, 4, .production_id = 10),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_declaration, 4, .production_id = 10),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_injection, 2),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_injection, 2),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(57),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(102),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(113),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_select_expression_repeat1, 2), SHIFT_REPEAT(82),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_select_expression_repeat1, 2),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2), SHIFT_REPEAT(50),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 6, .production_id = 2),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 1),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_clause, 5, .production_id = 11),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(85),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [234] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(34),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [239] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2), SHIFT_REPEAT(63),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 7, .production_id = 4),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function_declaration, 7, .production_id = 5),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit_type, 2),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_function_declaration, 6, .production_id = 3),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_clause, 6, .production_id = 11),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, .production_id = 1),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 5),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [320] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_structured_agent(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
